apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vote-api-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/praveen4g0/vote-api.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vote-api-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/vote-cicd/vote-api:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vote-ui-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/praveen4g0/vote-ui.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vote-ui-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/vote-cicd/vote-ui:latest
