---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: votecicd-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: vote-cicd-trig
      interceptors:
        - webhook:
            objectRef:
              kind: Service
              name: gh-validate
              apiVersion: v1
      bindings:
        - name: vote-cicd-pipelinebinding
      template:
        name: vote-cicd-triggertemplate