apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: votecicd-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: vote-cicd-trig
      bindings:
      - name: vote-cicd-pipelinebinding
      template:
        name: vote-cicd-triggertemplate
